### ISSUE TITLE
FBX embedded texture issue

### ISSUE THREAD

**Issue by MadhuiOS** [eugenebokhan/AssetImportKit#1]
@eugenebokhan Nice framework, but it is not loading embedded textures for FBX models, can you please look into that issue

**Comment by Kelmatou** [comment]
I had the same case today.
Figure it out that in my fbx files, texture folder had path prefixed with "\\" character, but Apple is using "/".
I fixed this by changing line 
`let texFileName = texFilePath.lastPathComponent`
by
`let texFileName = texFilePath.lastPathComponent.replacingOccurrences(of: "\\", with: "/")`
It shouldn't break anything for other formats, feel free to test and apply this change @eugenebokhan

**Comment by eugenebokhan** [comment]
Hi @Kelmatou! Thank you for your suggestion, it works 🙂

**Comment by eugenebokhan** [comment]
fixed in https://github.com/eugenebokhan/AssetImportKit/commit/599e897bfb69e0b5d0c5c55b086f86192d123a82

**Comment by eugenebokhan** [comment]
seems to be ok in my case
![img_0121](https://user-images.githubusercontent.com/8983647/51842604-51381180-2322-11e9-87c8-d886efe2da8f.PNG)
<img width="592" alt="screenshot 2019-01-28 at 17 28 52" src="https://user-images.githubusercontent.com/8983647/51842608-5301d500-2322-11e9-9874-b8879c762fc1.png">
