### ISSUE TITLE
How to guide is not ok

### ISSUE THREAD

**Issue by avianezbq** [eugenebokhan/AssetImportKit#2]
Hi!

First of all, thanks for your work ;)
I´m trying to use your framework inside my app, but it´s not so easy as you wrote in "How to install guide". When I add AssetImportKit.framework to my app, it always requests the whole AssetImportKit project... can you please help me or update the guide?

**Comment by eugenebokhan** [comment]
@avianezbq the easiest way is to use 'Cocoapods'.
