### ISSUE TITLE
Weird model import for fox with multiple animations

### ISSUE THREAD

**Issue by gabmedalv01** [eugenebokhan/AssetImportKit#6]
Hello, I have a problem trying to load a fbx model created on Blender using AssertImportKit on iOS. The problem is, if I remove animations the model is loaded ok but, if I export all the animations (using Blender), the imported model looks weird, (also if I import the model as a .dae it look ok but just with one animation). I also tried with the Mac SceneKitAssetImport and the result is the same. I attached a few screenshots of the behavior and the original fbx model
<img width="331" alt="Captura de Pantalla 2019-04-14 a la(s) 14 47 10" src="https://user-images.githubusercontent.com/38539704/56098311-d021fc80-5ec4-11e9-9a44-4e58df9220b8.png">
<img width="275" alt="Captura de Pantalla 2019-04-14 a la(s) 14 47 25" src="https://user-images.githubusercontent.com/38539704/56098312-d021fc80-5ec4-11e9-89e7-c5fac69bf618.png">

https://www.dropbox.com/s/t87jgou6ejgq6tk/newModelTest_4.fbx?dl=0

**Comment by eugenebokhan** [comment]
@gabmedalv01 this might be a problem of Assimp itself. Please check it.
