### ISSUE TITLE
I have a problem filePath 

### ISSUE THREAD

**Issue by asdfbinut** [eugenebokhan/AssetImportKit#7]
do {
            let assimpScene = try SCNScene.assimpScene(filePath: "art.scnassets/jill.obj",
                                                       postProcessSteps: [.debone])
            let modelScene = assimpScene.modelScene
            modelScene!.rootNode.childNodes.forEach {
                 sceneView.scene.rootNode.addChildNode($0)
           //     self.modelContainerNode.addChildNode($0)
            }
           // sceneView.scene.rootNode.addChildNode(modelContainerNode)
            sceneView.scene = modelScene!
        } catch {
            print(error.localizedDescription)
        }

**Comment by eugenebokhan** [comment]
@asdfbinut fixed in 1.1.0
