### ISSUE TITLE
Infinite loop in scene importer

### ISSUE THREAD

**Issue by jexe** [eugenebokhan/AssetImportKit#8]
Looks like [this code](https://github.com/eugenebokhan/AssetImportKit/blob/master/AssetImportKit/AssetImportKit/Extensions/SceneKit/SCNScene/SCNScene%20%2B%20AssetImport.swift#L65) in `ScnScene + AssetImport.swift` just calls itself repeatedly:

```
    public static func assimpScene(with url: URL,
                                   postProcessSteps: PostProcessSteps) throws -> AssetImporterScene {
        do {
            let scene = try assimpScene(with: url, postProcessSteps: postProcessSteps)
            return scene
        } catch {
            throw error
        }
    }
```

But couldn't find any useful initializer in `AssetImporter` to suggest a decent PR to fix. Should this method be removed?

**Comment by eugenebokhan** [comment]
@jexe fixed in 1.1.0
